import { getSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import Login from '../components/Login';
import Feed from '../components/Feed';

export default function Home({ session }) {
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Facebook 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/facebook-logo.svg" />
      </Head>
      <Header />

      <main className="flex bg-gray-100">
        {/* Leftside bar */}
        <Sidebar />

        {/* Feed (Create post and Posts) */}
        <Feed />
        {/* Right sidebar */}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: { session },
  };
}
