import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/facebook-logo.svg" />
      </Head>
      <Header />

      <main className="flex bg-gray-100">
        <Sidebar />
        {/* Leftside bar */}
        {/* Feed (Create post and Posts) */}
        {/* Right sidebar */}
      </main>
    </div>
  );
}
